# Generated by Django 5.2.8 on 2026-04-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='', upload_to='produtos/'),
            preserve_default=False,
        ),
    ]
