# Generated by Django 5.2.8 on 2026-06-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('projeto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
